spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${local-db.mysql.host}:${local-db.mysql.port}/${local-db.mysql.name}
    username: ${local-db.mysql.username}
    password: ${local-db.mysql.password}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    show-sql: true
    open-in-view: false


logging:
  level:
    org:
      hibernate:
        type: info